### ISSUE TITLE
Fee field is missing in Historical Trades request

### ISSUE THREAD

**Issue by Veniamin** [ccxt-dev/ccxt#337] opened 2017-10-18 07:20 UTC
Most crypto exchanges are returning Fee field in Historical Trades request, but there is no such field in library. Will it appear in the future or it's done specifically for some reason?

**Comment by kroitor** [comment] 2017-10-18 07:24
@Veniamin, that part of the unified private API is under heavy development right now, and we will add fees, of course (we are actually adding that already here and there)! If that answers your question I would close this issue if you don't mind as being somewhat duplicate of #71. Feel free to reopen it or just ask questions if any. Stay tuned for more updates! ;)

**Comment by Veniamin** [comment] 2017-10-18 07:25
Ok, thank you

**Closed** 2017-10-18 07:25 UTC
