### ISSUE TITLE
Gatecoin async fetch_balance problem

### ISSUE THREAD

**Issue by md0101** [ccxt-dev/ccxt#260] opened 2017-10-02 10:07 UTC
Hi, using version 1.8.98 on Python 3.6, I am getting the following error when calling the async fetch_balance function for Gatecoin

`Unclosed connection`
`client_connection: Connection<('api.gatecoin.com', 443, True)>`
`must be str, not bytes`

**Comment by kroitor** [comment] 2017-10-02 10:13
Hi! 

Please, read this: 
- https://github.com/ccxt-dev/ccxt/wiki/Manual#troubleshooting ?
- https://github.com/ccxt-dev/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Basically, 443 means rate-limiting or DDoS Protection. 
Can you try a proxy to see if it replies with the same result? 
When instantiating your Gatecoin instance, pass a proxy param along with your credentials like so:
```
gatecoin = ccxt.gatecoin ({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'proxy': 'https://cors-anywhere.herokuapp.com/',
})
print(gatecoin.fetch_balance())
```

Can you paste the output of the above snippet here?

**Comment by md0101** [comment] 2017-10-02 11:05
Hi yes it did seem that using the proxy produced the same 443 error.

Using the code snippet you have posted above, I get the following output

```
C:\Python36\python.exe C:/Users/Administrator/PycharmProjects/xx.py
https://cors-anywhere.herokuapp.com/https://api.gatecoin.com/Public/LiveTickers GET https://cors-anywhere.herokuapp.com/https://api.gatecoin.com/Public/LiveTickers 
Request: {'User-Agent': 'ccxt/1.8.98 (+https://github.com/kroitor/ccxt) Python/3.6.2', 'Origin': '*', 'Accept-Encoding': 'gzip, deflate'} None
Traceback (most recent call last):
  File "C:/Users/Administrator/PycharmProjects/xx.py", line 28, in <module>
    print(gatecoin.fetch_balance())
  File "C:\Users\Administrator\PycharmProjects\xx.py", line 10360, in fetch_balance
    self.load_markets()
  File "C:\Users\Administrator\PycharmProjects\xx.py", line 656, in load_markets
    markets = self.fetch_markets()
  File "C:\Users\Administrator\PycharmProjects\xx.py", line 10341, in fetch_markets
    response = self.publicGetPublicLiveTickers()
  File "C:\Users\Administrator\PycharmProjectsxxs.py", line 10531, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\Administrator\PycharmProjects\xx.py", line 220, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\Administrator\PycharmProjects\xx.py", line 273, in fetch
    print(method, url, "\nResponse:", response.info().headers, decoded_text)
AttributeError: 'HTTPMessage' object has no attribute 'headers'

Process finished with exit code 1
```

**Comment by kroitor** [comment] 2017-10-02 11:29
@md0101 ok, thank for reporting back. Now, I suggest, let's debug it a little... First, let's try a second proxy:
```
gatecoin = ccxt.gatecoin ({
    'proxy': 'https://crossorigin.me/',  # another proxy
    'verbose': True,
})
print(gatecoin.load_markets())  # the most basic method
```

1. Does the above snippet work?
2. What country are you from?
3. Is trading with Gatecoin website currently accessible to you?

I'll stand by for your reply and we will go on with troubleshooting it.

**Comment by md0101** [comment] 2017-10-02 13:07
Great thank you. 
Just conducted a successful trade via their website so no issues there.  I am based in the UK and with your basic method and alternative proxy, I get this output

```
C:\Python36\python.exe C:/Users/Administrator/PycharmProjects/ccxt/test.py
https://crossorigin.me/https://api.gatecoin.com/Public/LiveTickers GET https://crossorigin.me/https://api.gatecoin.com/Public/LiveTickers 
Request: {'User-Agent': 'ccxt/1.8.98 (+https://github.com/kroitor/ccxt) Python/3.6.2', 'Origin': '*', 'Accept-Encoding': 'gzip, deflate'} None
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\ccxt\ccxt\exchange.py", line 251, in fetch
    response = opener.open(request, timeout=int(self.timeout / 1000))
  File "C:\Python36\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "C:\Python36\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "C:\Python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Python36\lib\urllib\request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\Python36\lib\urllib\request.py", line 1321, in do_open
    r = h.getresponse()
  File "C:\Python36\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "C:\Python36\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Python36\lib\http\client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Python36\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "C:\Python36\lib\ssl.py", line 1002, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Python36\lib\ssl.py", line 865, in read
    return self._sslobj.read(len, buffer)
  File "C:\Python36\lib\ssl.py", line 625, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Administrator/PycharmProjects/ccxt/test.py", line 16, in <module>
    print(gatecoin.load_markets())  # the most basic method
  File "C:\Users\Administrator\PycharmProjects\ccxt\ccxt\exchange.py", line 656, in load_markets
    markets = self.fetch_markets()
  File "C:\Users\Administrator\PycharmProjects\ccxt\ccxt\exchanges.py", line 10341, in fetch_markets
    response = self.publicGetPublicLiveTickers()
  File "C:\Users\Administrator\PycharmProjects\ccxt\ccxt\exchanges.py", line 10531, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\Administrator\PycharmProjects\ccxt\ccxt\exchange.py", line 220, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\Administrator\PycharmProjects\ccxt\ccxt\exchange.py", line 254, in fetch
    raise RequestTimeout(' '.join([self.id, method, url, 'request timeout']))
ccxt.errors.RequestTimeout: gatecoin GET https://crossorigin.me/https://api.gatecoin.com/Public/LiveTickers request timeout

Process finished with exit code 1
```

**Comment by kroitor** [comment] 2017-10-02 15:19
Alright, now let's try a larger timeout:
```
gatecoin = ccxt.gatecoin ({
    'proxy': 'https://cors-anywhere.herokuapp.com/',  # better try with and without this line
    'verbose': True,
    'timeout': 30000, # in milliseconds
})
print(gatecoin.load_markets())  # the most basic method
```

Is it still not working? This is most likely a connectivity problem, but we'll need more feedback from you on this. Basically, we will eliminate all reasons one by one. Also, is there any way you can test the same code on a different computer (or a remote server) to see, if it's bound to your location or not. We need to eliminate these possible reasons first.

**Comment by md0101** [comment] 2017-10-03 16:57
Right I have to apologies to you @kroitor as I omitted to explain I have been running this on an Amazon AWS instance (region : us-west-2b) where I cannot get it to work, with or without a proxy and timeout.
It seems this is a location based problem though as there are no issues with running it from my local machine in the UK.

I would prefer to run in Amazon so if there is a solution you can propose I would be grateful. I can of course look to open an instance in another region if there is no other solution but I am mindful this could cause similar issues with other exchanges, so wondering if there is an alternative?  Thank you.

**Comment by kroitor** [comment] 2017-10-03 17:06
@md0101 hi! Well, it looks like either of the two:
1. Gatecoin itself being in Hong Kong may be limiting traffic from US. At least, we have a lot of other users who run ccxt against Gatecoin with no problem, and as you say it your self, running it from UK makes a difference, so it's not a code problem obviously. A workaround to this case would be to use a proxy or switch AWS instance location to another part of US or, maybe, somewhere in Europe.
2. That particular AWS instance may have a problem accessing Gatecoin due to its networking setup, you can run another cheap micro instance based in US to see if it makes a difference somehow.

Apart from that, I'm afraid, this problem is beyond our scope, because, it's likely related to a particular location, and for now we can't recommend anything other than going through our [troubleshooting sequence](https://github.com/ccxt-dev/ccxt/wiki/Manual#troubleshooting) from the Manual. A usual solution to this kind of problems is to switch locations until you find a good connection with target exchanges.

**Comment by kroitor** [comment] 2017-10-04 08:53
@md0101 so, I'm closing this issue for now if you don't mind, because the cause is now clear. Feel free to reopen it or just ask questions, if any. Thx for your feedback!

**Closed by kroitor** 2017-10-04 08:53 UTC
