### ISSUE TITLE
Margin trades examples

### ISSUE THREAD

**Issue by Fcl69** [ccxt-dev/ccxt#255] opened 2017-10-01 06:59 UTC
Hello,

I was going through manual, as well as several old posted issues, but was not able to find a relevant example of margin trading. For instance, Kraken and Bitfinex. I'm using Python, btw.
This issue (https://github.com/ccxt-dev/ccxt/issues/204) has an example for Kraken posted by you:
>>import ccxt
>>kraken = ccxt.kraken({'apiKey': 'YOURKEY', 'secret': 'YOURSECRET'})
>>order = kraken.create_market_sell_order('BTC/USD', 1, {'leverage': 2})
>>print(order) # should have an id
It's a bid off, it should be {'leverage-sell': 2}, but anyways either way it doesn't work.

Here is my code for Kraken:
>>order = exch.create_order('BTC/USD', 'market', 'sell', 0.01, {'leverage_sell': 3})

It actually created an order and did a trade. But! It was a regular market order, not margin: https://cl.ly/2C46331U0X1s

Furthermore, this is the code I have for bitfinex (according to their API documentation):
>>order = exch.create_order('BTC/USD', 'market', 'buy', 0.01, {'type': 'margin'})
And here is the error:
  File "/usr/local/lib/python3.6/site-packages/ccxt/exchanges.py", line 2585, in create_order
    raise NotSupported(self.id + ' createOrder not implemented yet')
ccxt.errors.NotSupported: bitfinex2 createOrder not implemented yet
"not implemented yet"? o_O

So I guess, what I'm trying to ask is, could you please update the documentation with few more relevant examples of margin trading? To highlight few usecases of using {params}. Thank you,

**Comment by kroitor** [comment] 2017-10-01 07:15
Hi, @Fcl69!

For Kraken:

```Python
import ccxt

kraken = ccxt.kraken ({
    # 'apiKey': 'YOUR_API_KEY',
    # 'secret': 'YOUR_SECRET',
})

kraken.load_markets ()

for symbol in kraken.symbols:
    print(symbol,
        'Available leverage levels',
        'Buy:', kraken.markets[symbol]['info']['leverage_buy'],
        'Sell:', kraken.markets[symbol]['info']['leverage_sell'])

# it should be "leverage", not "leverage_sell" nor "leverage-sell"
kraken.create_order('BTC/USD', 'market', 'sell', 0.01, {'leverage': 3}) 
```

For bitfinex2 – this is their experimental Bitfinex API v2 (it's raw and they don't guarantee that it works), and v2 does not offer an endpoint for creating orders at all. This is not because we can't implement it, it's just because their v2 does not offer that yet. So, for trading with Bitfinex, use v1 (the stable version of it).

Does this answer your question?

**Comment by kroitor** [comment] 2017-10-01 07:20
I edited the above example for Kraken a little, let me know if you still have questions with it.

**Comment by Fcl69** [comment] 2017-10-01 07:58
It did work with Kraken, thank you!
And thank you for explaining about bitfinex2. H/e could you please send an example for bitfinex margin order as well? I'm a bit confused at this stage... I'd like to go with:
order = exch.create_market_buy_order(symbol, trade_amount, {'type': 'margin'})

But https://docs.bitfinex.com/v1/reference#rest-auth-new-order says:
>>Either “market” / “limit” / “stop” / “trailing-stop” / “fill-or-kill” / “exchange market” / “exchange
>> limit” / “exchange stop” / “exchange trailing-stop” / “exchange fill-or-kill”. (type starting by
>> “exchange ” are exchange orders, others are margin trading orders)
"others are margin trading orders". So how should I deal with a default "market" to makge it margin?

**Comment by kroitor** [comment] 2017-10-01 08:09
By default, Bitfinex v1 will create an order of type `exchange market (if you are calling `create_market_buy_order()`). You will have to redefine the type for `market`, as you wrote it. So, you can go ahead with this line (it should work with v1):
```Python
exch.create_market_buy_order(symbol, trade_amount, {'type': 'market'})
```

**Comment by Fcl69** [comment] 2017-10-01 08:14
it worked! thank you so much for the prompt replies!

**Comment by kroitor** [comment] 2017-10-01 08:15
Thanks for reporting back! I'm closing this issue if you don't mind. Feel free to ask your questions, if you have any left.

**Closed by kroitor** 2017-10-01 08:15 UTC

**Comment by udvarid** [comment] 2017-11-14 15:28
Hello. 
How should I redefint the type for market in order to use the margin trade at bitfinex via API?

**Comment by kroitor** [comment] 2017-11-14 15:34
Hi, @udvarid !


1. To create a market order of default type (which is `exchange market`):

A. `exch.create_market_buy_order(symbol, trade_amount)` ←↓ this is an exchange order
B. `exch.create_market_buy_order(symbol, trade_amount, {'type': 'exchange market'})`

Options A and B are equivalent for exchange orders.

2. To create a market margin order of type `market`:

    `exch.create_market_buy_order(symbol, trade_amount, {'type': 'market'})` ← this is a margin order

**Comment by udvarid** [comment] 2017-11-14 21:23
Thank you!
And any idea how to get my open margin positions with here? The fetch_balance() is only give my balances (exchange and margin) but it would be nice if I could see the open margin positions as well.

Thank you in advance!

**Comment by kroitor** [comment] 2017-11-14 21:27
@udvarid sure, see here: https://github.com/ccxt/ccxt/issues/318. Hope it helps (it should).

**Comment by udvarid** [comment] 2017-11-14 21:45
thank you very much!
On 2017. Nov 14., at 22:27, Igor Kroitor <notifications@github.com<mailto:notifications@github.com>> wrote:


@udvarid<https://github.com/udvarid> sure, see here: #318<https://github.com/ccxt/ccxt/issues/318>. Hope it helps (it should).

**Comment by fedecaccia** [comment] 2018-02-28 18:23
Hello! How can I get the trade balance? I'm using private_post_trade_balance() but I get this error:
raise ExchangeError(self.id + ' ' + self.json(response))
ccxt.base.errors.ExchangeError: kraken {"error":["EGeneral:Internal error"]}

**Comment by kroitor** [comment] 2018-02-28 22:01
@fedecaccia, please, post a minimal, but a complete snippet of code that I could copypaste into my python to reproduce it (without the keys), without seeing the code it's hard to tell.

**Comment by fedecaccia** [comment] 2018-03-01 18:17
Hi, thanks for your responde. While I was writng the code, I recognize that I was using type="maker" instead of type="market". Thanks!

**Comment by kroitor** [comment] 2018-03-02 01:12
@fedecaccia thx for reporting back!

**Comment by ChacoLv** [comment] 2018-09-04 09:40
@kroitor how can I get my bitfinex margin position information?
I try to do it by exch.fetch_my_trades(symbol=symbol,params=params)
params = {'type': 'trading'}
but it result is all my history order information ,is not my real margin position information.

**Comment by kroitor** [comment] 2018-09-04 09:47
@ChacoLv https://github.com/ccxt/ccxt/search?q=bitfinex+position&type=Issues

**Comment by ChacoLv** [comment] 2018-09-04 09:50
@kroitor OK,Get it ,Thank you
