### ISSUE TITLE
fetch_ohlcv since problem

### ISSUE THREAD

**Issue by werewere** [ccxt-dev/ccxt#379] opened 2017-10-23 20:25 UTC
Hi, I'm not sure if this is a bug or a feature; the following code won't work:

```
since=int(datetime.datetime.strptime('2017-10-23 00:00:00', '%Y-%m-%d %H:%M:%S').strftime("%s"))
ohlc=polo.fetch_ohlcv("ETH/BTC", '5m', since)
```
It is needed to do the following: 
```
since=int(datetime.datetime.strptime('2017-10-23 00:00:00', '%Y-%m-%d %H:%M:%S').strftime("%s"))
since *=1000
ohlc=polo.fetch_ohlcv("ETH/BTC", '5m', since)
```
I found this because checking the ccxt source code, I saw that (in Poloniex at least) the start time was calculated doing:

`'start': int(since / 1000),`

May be this is due to an old problem in Poloniex (I'm just guessing) and then Poloniex fixed the problem but the ccxt code still has the old workaround?. Anyway, this is not a problem, I can just multiply, but I'm not sure if I'm missing something.

**Comment by kroitor** [comment] 2017-10-23 20:30
Hi, @werewere ! Nope, it's not a bug, the library works with all timestamps as milliseconds, everywhere. So, yes, you can just do `ohlc=polo.fetch_ohlcv("ETH/BTC", '5m', since * 1000)`. If that answers your question, please, close this issue. Thx!

**Closed** 2017-10-23 20:34 UTC
Labels: question

**Comment by werewere** [comment] 2017-10-23 21:19
Yeah, I use also Bitfinex but as it is not fully supported yet for OHLCV, I was doing tests with Poloniex.

Anyway, understood, thanks! :)

**Comment by kroitor** [comment] 2017-10-23 21:21
@werewere bitfinex v2 already supports OHLCV btw ;) And, hopefully, both of them will support it soon ;)

**Comment by werewere** [comment] 2017-10-23 21:41
Oh, it is true! I didn't realized that I should use bitfinex2, indeed it has OHLCV!  You made my day :)

**Comment by kroitor** [comment] 2017-10-23 22:17
@werewere as of version 1.9.237 you can use Bitfinex v1 to fetch_ohlcv() as well ;) Cheers!

**Comment by xgdgsc** [comment] 2017-11-19 06:36
Has the since API changed? `bar_list=bitmex.fetch_ohlcv('XBTZ17', '1m', since='2017-11-08 00:01:44')` works in version `'1.9.39'` but not in version `'1.10.171'`

**Comment by kroitor** [comment] 2017-11-19 06:43
@xgdgsc it accepts an integer number of milliseconds for consistency across the majority of exchanges, so you can call it like so:

```Python
bar_list=bitmex.fetch_ohlcv('XBTZ17', '1m', since=bitmex.parse8601('2017-11-08 00:01:44'))
```

**Comment by xgdgsc** [comment] 2017-11-19 07:05
OK.
