### ISSUE TITLE
How to get withdrawal fee (txFee) for any supported cryptocurrency?

### ISSUE THREAD

**Issue by mazertwo** [ccxt-dev/ccxt#378] opened 2017-10-23 16:17 UTC
For Polo i use: public_get_returncurrencies()

Does ccxt have universal method?

**Comment by kroitor** [comment] 2017-10-23 16:19
Hi, @mazertwo! Sorry, but this issue is a duplicate of this: https://github.com/ccxt-dev/ccxt/issues/40. I suggest let's move our discussion there, if you have questions after reading what's already there ;)

**Closed by kroitor** 2017-10-23 16:19 UTC
Labels: duplicate, question
