### ISSUE TITLE
kraken {"error":["EAPI:Invalid nonce"]}

### ISSUE THREAD

**Issue by Fcl69** [ccxt-dev/ccxt#253] opened 2017-09-30 10:24 UTC
Python3.6 when calling:
                exch = ccxt.kraken({
                    'apiKey': key,
                    'secret': secret
                    })
                  balance = exch.fetch_balance()

I got the following error:
Traceback (most recent call last):
  File "margin.py", line 77, in __init__
    balance = exch.fetch_balance()
  File "/usr/local/lib/python3.6/site-packages/ccxt/exchanges.py", line 12727, in fetch_balance
    response = self.privatePostBalance()
  File "/usr/local/lib/python3.6/site-packages/ccxt/exchanges.py", line 12878, in request
    raise ExchangeError(self.id + ' ' + self.json(response))
ccxt.errors.ExchangeError: kraken {"error":["EAPI:Invalid nonce"]}

Worked with new key and old keys - same issue. Keys and secrets are correct (later ends with ==)
Any suggestions?

**Comment by kroitor** [comment] 2017-09-30 10:29
Hi, first, there's a nonce window which you can set on Kraken. This would allow you to overcome time synch issues, if this is the case.

Try the following snippet and report if it's working for you or not:
```Python
exch = ccxt.kraken({
'apiKey': 'LKK6fmUbkSw/yZ7mnIs+1TDEQanqXmSD235XHIu2DU4Z3MZOR28RNKAk',
'secret': 'PBA/aEa6UFDKnWIV+syxSwYQhjZUV0piFr/iL+icaBWyFp1gD4ewAc45jdL54G4ox6ztaBSPalvMq6tuzO9tZA==',
})
balance = exch.fetch_balance()
print(balance)
```

This is a new key, and it should work (works for me, I just tested it). If it doesn't work for you... well, what's your system time / location ?

**Comment by Fcl69** [comment] 2017-09-30 10:40
Yes, this code works fine:
>>{'info': {}}

I've udpated nonce window from 0 to 10 (https://cl.ly/1U0D2g1S432W), but it didn't help. Still says it's ccxt.errors.ExchangeError: kraken {"error":["EAPI:Invalid nonce"]}

Systime: Sat Sep 30 03:39:20 PDT 2017
Location is PST, so it's accurate.

**Comment by kroitor** [comment] 2017-09-30 10:43
Ok, can you create a new keypair and try putting it into the snippet I posted above to see the result? 

If it worked with my new key, it should work with your new key as well. If that is the case, the problem is related to your old keypair, which has been used with a large nonce previously, so it's usually easily solved by creating a new pair of keys. 

Also, we had a user that defined keys in two places in his code, and he could not find where the error came from, so, if you have some convoluted architecture, ensure that there's just one such place where you store the keys to eliminate duplication and bogus keys.

Please report if your new keypair worked with that snippet above. If not we will continue the troubleshooting process further.

**Comment by Fcl69** [comment] 2017-09-30 10:51
Yeah, it worked with a newly generated kraken key.
Thank you for helping out and sorry for bugging, feel free to close the issue.
If you don't mind, could you please elaborate on details, how could it actually happen with all my rest kraken keys become obsolete? 


PS It's a wonderful project, gentlemen, thank you very much for your effort.

**Comment by kroitor** [comment] 2017-09-30 10:55
> If you don't mind, could you please elaborate on details, how could it actually happen with all my rest kraken keys become obsolete?

You probably used them with other software, or with an example that uses a larger (redefined) nonce. This is [described here](https://github.com/ccxt-dev/ccxt/wiki/Manual#overriding-the-nonce) in details. Actually, we would recommend to read entire Manual very carefully, there's a lot of useful info there. It's for your own good. Also, note, that if you want to do frequent requests one by one, you should use a redefined milliseconds()-nonce, and for that you will have to read the Manual ) 

Best wishes and thanks for your feedback! Let us know if you have any other questions or difficulties with it. I'm closing this for now.

**Closed by kroitor** 2017-09-30 10:55 UTC

**Comment by kroitor** [comment] 2017-09-30 10:57
More to it: 

https://github.com/ccxt-dev/ccxt/wiki/Manual#authentication
https://github.com/ccxt-dev/ccxt/wiki/Manual#rate-limit

**Comment by dashersw** [comment] 2017-12-02 13:39
I solved this by using microseconds for the nonce, 

`nonce () { return this.microseconds() }`

**Comment by kroitor** [comment] 2017-12-02 19:07
@dashersw thanks for reporting back!

**Comment by superquantum** [comment] 2022-05-06 08:06
> I solved this by using microseconds for the nonce,
> 
> `nonce () { return this.microseconds() }`

@kroitor Igor its worked to me too. i wanted to send money." error: EAPI" i gave. after i changed and its worked. thanks @dashersw (teşekkürler dostum)

**Comment by kroitor** [comment] 2022-05-06 10:19
Another solution to it is to recreate your API keys (if you have used them with some other software before – it will screw your nonce up too high).
