### ISSUE TITLE
Yobit concrete order cancel

### ISSUE THREAD

**Issue by mazertwo** [ccxt-dev/ccxt#310] opened 2017-10-11 16:04 UTC
How to cancel Yobit limit order?
How to get order ID after buying?

fetch_open_orders() wont work

ccxt.errors.NotSupported: yobit fetch_open_orders() not implemented yet

Thank you!

**Comment by kroitor** [comment] 2017-10-11 16:23
Hi, @mazertwo !

> How to cancel Yobit limit order?

Hmm... How about calling `.cancelOrder()` or `.cancel_order()`, just like you would do with any other exchange?

> How to get order ID after buying?

Read the Manual once and for all? ;)
https://github.com/ccxt-dev/ccxt/wiki/Manual#placing-orders

> fetch_open_orders() wont work

Orders API is in progress, not all unified order methods are implemented yet, this point is a duplicate of #71. We will implement it soon or you can submit your implementation if you would like to help us with that. In the meantime you can use their custom API built into ccxt to fetch their orders.

Does the above answer your questions?

**Comment by mazertwo** [comment] 2017-10-11 16:46
Kroitor, but how i get order id after buying on the YoBit? Sorry for newbie question.

**Comment by kroitor** [comment] 2017-10-11 16:57
@mazertwo did you read the Manual? Because it's written there:

```
your_new_order = yobit.create_order (...)
print(your_new_order['id'])  # ← this is how you get an id of an order you just created
```

**Comment by mazertwo** [comment] 2017-10-11 17:01
Ohhh, shure, thank you so much! Today i'm done with programming :))))

**Comment by kroitor** [comment] 2017-10-11 17:05
@mazertwo no problem ) Is it ok if I close this now?

**Closed** 2017-10-11 17:25 UTC
