### ISSUE TITLE
Symbols naming inconsistencies

### ISSUE THREAD

**Issue by mazertwo** [ccxt-dev/ccxt#302] opened 2017-10-10 11:32 UTC
ANI ANICoin(yobit) AnimeCoin(cryptopia)
BTS Bitshares2(yobit) Bitshares(bter)
IOT IOTA(bitfinex) IoTcoin(ccex)

**Comment by kroitor** [comment] 2017-10-10 11:32
?

**Comment by mazertwo** [comment] 2017-10-10 11:36
Upd, accidentally push key on the keyboard :)

**Comment by kroitor** [comment] 2017-10-10 11:49
For IOTA we think like using 4 letters (IOTA) because it's more common than 3 letters (IOT). But for now I'll fix IoTcoin on ccex.

**Comment by kroitor** [comment] 2017-10-10 12:01
Ok those three should be fixed in 1.9.94+ (in 5 minutes). Thx a lot for the hint!

**Closed** 2017-10-10 12:00 UTC

**Comment by kroitor** [comment] 2017-10-10 12:07
The build is there, thx once again for your attention! Let us know if you find more! )

**Comment by Nitrooo** [comment] 2017-10-11 13:59
Also in binance class USD is referred as "USDT". Shouldn't it be "USD", for consistency?

**Comment by kroitor** [comment] 2017-10-11 17:56
@Nitrooo , see here:
- #182 
- https://github.com/ccxt-dev/ccxt/issues/298#issuecomment-335349884

> We're not sure that we should force that conversion for all exchanges, but for the ones that clearly claim that (HitBTC) – we think that is appropriate. If we can somehow ensure that USDT is indeed liquid for the same nominal amounts of USD, then there would be no problem to add that correction as well.

> So, I guess, now we need to make sure that:
> - USD indeed equals USDT
> - USDT is dominating the majority of exchanges, even those that name it USD

We would be very happy if you help us with USD ←→ USDT consistency.

**Comment by kroitor** [comment] 2017-10-11 17:58
@Nitrooo in other words, I could not find it stated clearly anywhere on the internet, and we can't just go ahead and make that substitution until someone guarantees that USD = USDT, universally.

**Comment by Nitrooo** [comment] 2017-10-11 18:18
Whoops, USDT is actually not US Dollar, but Tether USD, a cryptocurrency. At least on Binance:
[https://support.binance.com/hc/en-us/articles/115001093991-Tether-USD-USDT-]()

**Comment by kroitor** [comment] 2017-10-11 18:25
@Nitrooo the problem is: some exchanges say that they trade UST, while actually trading USDT. They are all inconsistent and their docs are not very supportive in that sense. This is what we have to deal with. So for every exchange where those currencies are present, we need to find out the true meaning behind USD and USDT.
