### ISSUE TITLE
Poloniex Nonce error

### ISSUE THREAD

**Issue by mazertwo** [ccxt-dev/ccxt#319] opened 2017-10-14 17:28 UTC
This small code: 

import ccxt
poloniex = ccxt.poloniex()
poloniex.apiKey = 'xxxxxxxxxxxxxxxxxxxxxxxxx'
poloniex.secret = 'xxxxxxxxxxxxxxxxxxxxxxxxxx'
print(poloniex.private_post_getmarginposition({'currencyPair': 'BTC_XMR'}))
print(poloniex.private_post_returnmarginaccountsummary())
marginbalance = poloniex.private_post_returnmarginaccountsummary()
print(marginbalance['totalValue'])

produce strange error 

ccxt.errors.ExchangeNotAvailable: poloniex POST https://poloniex.com/tradingApi 422   {"error":"Nonce must be greater than 1508002069. You provided 1508002069."}

**Comment by kroitor** [comment] 2017-10-14 17:30
It's not strange. Please read either of the following:
- the Manual (it's written there)
- or this: https://github.com/ccxt-dev/ccxt/issues/274

Sorry, but I'm closing this issue as a duplicate.

**Closed by kroitor** 2017-10-14 17:30 UTC

**Comment by mazertwo** [comment] 2017-10-14 17:32
I made new keypair, but still same. May be (here[https://github.com/rferro/plnx/issues/2](url)) same trouble?

**Comment by kroitor** [comment] 2017-10-14 17:34
@mazertwo: the problem is not your keypair, but the frequency of your requests. There should be a pause between them. Poloniex, as well as all other exchanges, won't let you send your requests to quickly, all in a split second. You should make a delay to stay below rate limit, otherwise you'll get banned by the exchange. If you want ccxt to make a pause for you, do this:

```Python
import ccxt
poloniex = ccxt.poloniex()
poloniex.enableRateLimit = True  # ←--------------- this line
poloniex.apiKey = 'xxxxxxxxxxxxxxxxxxxxxxxxx'
poloniex.secret = 'xxxxxxxxxxxxxxxxxxxxxxxxxx'
print(poloniex.private_post_getmarginposition({'currencyPair': 'BTC_XMR'}))
print(poloniex.private_post_returnmarginaccountsummary())
marginbalance = poloniex.private_post_returnmarginaccountsummary()
print(marginbalance['totalValue'])
```

**Comment by kroitor** [comment] 2017-10-14 17:44
There's a ton of info on this in the Manual, in other posts linked to this issue above, and in the examples as well.

**Comment by mazertwo** [comment] 2017-10-14 17:46
poloniex.enableRateLimit = True
and 
sleep (1) 
after every order helps me.

Thank you!

**Comment by kroitor** [comment] 2017-10-14 17:49
`sleep (1)` is not needed, the first line does the same inside. You should choose either `enableRateLimit` or `sleep`, otherwise you are making a double-delay (getting slower than you could).

**Comment by mazertwo** [comment] 2017-10-14 17:51
I set sleep (2). Witout sleep or with sleep (1) works not stable.

**Comment by kroitor** [comment] 2017-10-14 17:54
@mazertwo then there may be a bug inside the internal rate limiter, I'll take a deeper look into it. Thx for reporting!

**Comment by mazertwo** [comment] 2017-10-14 20:52
Anyway, enableRateLimit and sleep with any secconds doesnt help. I get nonce error with Poloniex at 70% cases.

**Comment by kroitor** [comment] 2017-10-14 20:53
@mazertwo ok, then paste your code to reproduce the error please, and we'll see what's going on.

**Comment by kroitor** [comment] 2017-10-14 21:09
Btw, I just noticed, that you have two subsequent calls to the same method `poloniex.private_post_returnmarginaccountsummary()`... Why would you do that?

This is how it should look like:
```Python
import ccxt
poloniex = ccxt.poloniex()
poloniex.enableRateLimit = True
poloniex.apiKey = 'xxxxxxxxxxxxxxxxxxxxxxxxx'
poloniex.secret = 'xxxxxxxxxxxxxxxxxxxxxxxxxx'
print(poloniex.private_post_getmarginposition({'currencyPair': 'BTC_XMR'}))
marginbalance = poloniex.private_post_returnmarginaccountsummary()  # no need to call it twice here
print(marginbalance)
print('Total value:', marginbalance['totalValue'])
```

This code works for me and does not break in 100% cases.

**Comment by kroitor** [comment] 2017-10-14 21:12
We'll be waiting to see a snippet that you have a problem with, after enabling the rate limit.

**Comment by mazertwo** [comment] 2017-10-14 21:19
`from time import sleep
import ccxt

poloniex = ccxt.poloniex()
poloniex.enableRateLimit = True
poloniex.apiKey = 'xxxxxxxxx'
poloniex.secret = 'xxxxxxxxxx'

while True:

 exch1 = poloniex

 pairs = ['ETH/BTC','XRP/BTC','LTC/BTC','XMR/BTC','STR/BTC','DASH/BTC','BTS/BTC','DOGE/BTC','FCT/BTC','MAID/BTC']

 gap = 0.10
 timeframe_sec = 1800

 buyorders=[]
 sellorders=[]

 for pair in pairs:

  orderbook = exch1.fetch_order_book(exch1.market(pair))

  bid = orderbook['bids'][0][0] if len (orderbook['bids']) > 0 else None
  ask = orderbook['asks'][0][0] if len (orderbook['asks']) > 0 else None

  margin1balance = exch1.private_post_returnmarginaccountsummary()
  exch1balance = float(margin1balance['totalValue'])/2

  exch1.load_markets()

  buyorders.append(exch1.private_post_marginbuy({'currencyPair': exch1.marketId(pair),'rate': bid-bid*gap,'amount': 2.4*((exch1balance/float(len(pairs)))/(bid-bid*gap))}))
  sleep(5)
  sellorders.append(exch1.private_post_marginsell({'currencyPair': exch1.marketId(pair),'rate': ask+ask*gap,'amount': 2.4*((exch1balance/float(len(pairs)))/(ask+ask*gap))}))
  sleep(5)

 sleep(timeframe_sec)

 for buyorder in buyorders:
     exch1.cancel_order(buyorder['orderNumber'])
     sleep(5)
 for sellorder in sellorders:
     exch1.cancel_order(sellorder['orderNumber'])
     sleep(5)`

**Comment by mazertwo** [comment] 2017-10-14 21:21
Just simple gap catcher :)

**Comment by kroitor** [comment] 2017-10-14 21:21
Three backticks ) 3 of them... &#96;&#96;&#96; ... )

**Comment by mazertwo** [comment] 2017-10-14 21:23
```
from time import sleep
import ccxt

poloniex = ccxt.poloniex()
poloniex.enableRateLimit = True
poloniex.apiKey = 'xxxxxxxxxxxxxxxxxxxxxx'
poloniex.secret = 'xxxxxxxxxxxxxxxxxxxxxxx'

while True:

 exch1 = poloniex

 pairs = ['ETH/BTC','XRP/BTC','LTC/BTC','XMR/BTC','STR/BTC','DASH/BTC','BTS/BTC','DOGE/BTC','FCT/BTC','MAID/BTC']

 gap = 0.10
 timeframe_sec = 1800

 buyorders=[]
 sellorders=[]

 for pair in pairs:

  orderbook = exch1.fetch_order_book(exch1.market(pair))

  bid = orderbook['bids'][0][0] if len (orderbook['bids']) > 0 else None
  ask = orderbook['asks'][0][0] if len (orderbook['asks']) > 0 else None

  margin1balance = exch1.private_post_returnmarginaccountsummary()
  exch1balance = float(margin1balance['totalValue'])/2

  exch1.load_markets()

  buyorders.append(exch1.private_post_marginbuy({'currencyPair': exch1.marketId(pair),'rate': bid-bid*gap,'amount': 2.4*((exch1balance/float(len(pairs)))/(bid-bid*gap))}))
  sleep(5)
  sellorders.append(exch1.private_post_marginsell({'currencyPair': exch1.marketId(pair),'rate': ask+ask*gap,'amount': 2.4*((exch1balance/float(len(pairs)))/(ask+ask*gap))}))
  sleep(5)

 sleep(timeframe_sec)

 for buyorder in buyorders:
     exch1.cancel_order(buyorder['orderNumber'])
     sleep(5)
 for sellorder in sellorders:
     exch1.cancel_order(sellorder['orderNumber'])
     sleep(5)
```

**Comment by kroitor** [comment] 2017-10-14 21:31
Yay! That's much better! ) And much easier to read )
Next time don't forget to add a Python word ) For highlighting and readability )

&#96;&#96;&#96;Python

your_code

&#96;&#96;&#96;

So, you're getting the nonce error with that code? Are you sure it's a nonce error, not any other error? Also, are you sure the code above actually works? I'm asking, because...
```
sleep(timeframe_sec)
```
This ↑ line looks like it's incorrect and the code can't work at all, you can't sleep for 1800 seconds. It's 8 minutes of waiting. Are you sure you use the same code, that you pasted? Because the pasted version does not seem to be workable at all.
Also, what's your version of ccxt?

Once again, three questions:
1. Are you sure the errors are related to a nonce problem?
2. Are you sure that this is the actual code?
3. What's your version of ccxt?

**Comment by mazertwo** [comment] 2017-10-14 21:35
yes, it my timeframe, 30 mins. Ccxt updated yesterday. All work, but in 70% cases a get Nonce error.

**Comment by kroitor** [comment] 2017-10-14 21:37
Ok, try this:

```Python
from time import sleep
import ccxt

poloniex = ccxt.poloniex()
poloniex.enableRateLimit = True
poloniex.apiKey = 'xxxxxxxxxxxxxxxxxxxxxx'
poloniex.secret = 'xxxxxxxxxxxxxxxxxxxxxxx'

while True:

 exch1 = poloniex

 pairs = ['ETH/BTC','XRP/BTC','LTC/BTC','XMR/BTC','STR/BTC','DASH/BTC','BTS/BTC','DOGE/BTC','FCT/BTC','MAID/BTC']

 gap = 0.10
 timeframe_sec = 1800

 buyorders=[]
 sellorders=[]

 for pair in pairs:

  orderbook = exch1.fetch_order_book(exch1.market(pair))

  bid = orderbook['bids'][0][0] if len (orderbook['bids']) > 0 else None
  ask = orderbook['asks'][0][0] if len (orderbook['asks']) > 0 else None

  margin1balance = exch1.private_post_returnmarginaccountsummary()
  exch1balance = float(margin1balance['totalValue'])/2

  sleep(5)  # ←----------------------------------------- added a delay between two requests here

  exch1.load_markets()

  buyorders.append(exch1.private_post_marginbuy({'currencyPair': exch1.marketId(pair),'rate': bid-bid*gap,'amount': 2.4*((exch1balance/float(len(pairs)))/(bid-bid*gap))}))
  sleep(5)
  sellorders.append(exch1.private_post_marginsell({'currencyPair': exch1.marketId(pair),'rate': ask+ask*gap,'amount': 2.4*((exch1balance/float(len(pairs)))/(ask+ask*gap))}))
  sleep(5)

 sleep(timeframe_sec)

 for buyorder in buyorders:
     exch1.cancel_order(buyorder['orderNumber'])
     sleep(5)
 for sellorder in sellorders:
     exch1.cancel_order(sellorder['orderNumber'])
     sleep(5)
```

**Comment by mazertwo** [comment] 2017-10-14 21:40
Does i need to delete other Sleep (5)?

**Comment by kroitor** [comment] 2017-10-14 21:41
Nope, leave them all where they are. Just add one more there, and you can delete the `load_markets()` (unnecessary after a fetch_order_book, it's only needed in the beginning, otherwise markets are loaded by fetch_order_book, inside the lib).

**Comment by kroitor** [comment] 2017-10-14 21:47
Also, your order of requests does not seem to be correct.

You fetch the orderbooks. Then you fetch the balance. By the time you get the balance, the orderbook on Poloniex could have changed. So you need to fetch the balance first, then fetch the orderbook, because your balance cannot change suddenly, the balance can only change due to your actions, whereas the orderbook can change between calls (as a result of other peoples' actions). So, you definitely need to fetch the balance first, the order book second. Switch their places. Your goal is to keep smallest possible delay between fetching the order book, calculating the price and making an order, so that it will not have a chance to change, or that chance will be lowered to a minimum smallest time, like 1 second.

**Comment by mazertwo** [comment] 2017-10-14 21:56
Igor, you great man!  I add sleep (1) before every order operation, and ta da... work correctly :)
Будешь в Питере, напиши. Угощу Ж)
Отдельное спасибо за советы по вызову сначала баланса, потом ордеров, я все понял.

**Comment by kroitor** [comment] 2017-10-14 22:00
Hooray, good to know you figured it out ) Let us know if you have other difficulties with it. Cheers )
Спасибо ;)

**Comment by kroitor** [comment] 2017-10-14 22:15
P.S.

1. Rate limit on Poloniex is 6 times per second = 1000 / 6 ≈ 170 milliseconds.
2. if you update to latest version of ccxt (as of today), you can set a minimal sleep of `sleep (1000.0/6.0)` ;) This is somewhat more efficient, than waiting 1 second.

**Comment by mazertwo** [comment] 2017-10-14 23:01
After update, work without sleep(). Brilliance work and support! Thank you!

**Comment by kroitor** [comment] 2017-10-14 23:01
@mazertwo awesome! Cheers!
