### ISSUE TITLE
fetchTicker() en masse incorrect treatment of base/quote volume

### ISSUE THREAD

**Issue by mkutny** [ccxt-dev/ccxt#284] opened 2017-10-07 06:42 UTC
Looks like a result of copypaste which is spread over all exchanges.

I don't think it wise to check with all the API docs for all exchanges to determine if they indeed return base or quote. I believe it would be quite safe to assume that if exchange provides only one volume than treat it as `baseVolume` rather than `quoteVolume`.

**Comment by mkutny** [comment] 2017-10-07 07:22
A nice addition would be to fill `quoteVolume` (in case it's `undefined`) with `baseVolume * vwap` along the way.

**Comment by kroitor** [comment] 2017-10-07 09:36
Hi, @mkutny ! Thx for your time investigating this! I'll fix that asap for all exchanges, and will add more tests to it. Really appreciate your help!

**Comment by kroitor** [comment] 2017-10-07 10:04
Ok, I fixed most of those bugs, but there may still be some issues with it, I'll test and debug further to bring it all to a consistent return. The bug was caused by the fact, that we had only one volume for the tickers initially, and then it was split into base/quote with some errors left over. Hope to fix them all. Thx again for your help! I'm closing this for now, if you don't mind. Feel free to reopen it if needed. I'll continue the work on this anyway.

**Closed by kroitor** 2017-10-07 10:04 UTC

**Comment by kroitor** [comment] 2017-10-07 10:08
P.S. The fixed version is coming up in approx 2 minutes. Thx!

**Comment by mkutny** [comment] 2017-10-07 15:35
Actually, I just ran a simple smoke test on 1.9.59 (just `BTC/USD` pair):

```
'use strict'

const ccxt = require ('ccxt');
const exchanges = ccxt.exchanges;

(async () => {
for (let i = 0; i < exchanges.length; i++) {
  const id = exchanges[i];
  const exchange = new ccxt[id] ();
  try {
    const ticker = await exchange.fetchTicker('BTC/USD');
    if (ticker.baseVolume == undefined || ticker.baseVolume > ticker.quoteVolume) {
      console.log(id, ticker.baseVolume, ticker.quoteVolume);
    }
  } catch (e) {
    // these don't quote in USD (or just not accessible)
  }
}
}) ();
```
What I've got is:
```
bitbay undefined 4.70222414
bitfinex2 undefined 16925.54092995
bitlish undefined undefined
coinfloor undefined 18.6501
coinmarketcap undefined 918644000
coinsecure 2316000000 668495474
fybse undefined 0.0370270312
fybsg undefined 4.33956766
gatecoin undefined 1319.66810865
gdax undefined 4996.88767076
huobipro 1254.2214 88.4188633339
independentreserve 44.90041288 0.03696869
itbit undefined 1023.2192
lakebtc undefined 1285.864735
livecoin undefined 464.82359383
mixcoins undefined 111.6665
okcoincny undefined 2012.353
okcoinusd undefined 47.682
okex undefined 515954
quadrigacx undefined 5.64532372
southxchange undefined 0.33816411
vaultoro undefined 150.504
```

Those which have `undefined` as `baseVolume` and up to five digit figures as `quoteVolume` are just leftovers after the split.

Some figures seem to be just insane, in particular:
```
coinsecure 2316000000 668495474
huobipro 1254.2214 88.4188633339 (1254 / 88 = 14)
independentreserve 44.90041288 0.03696869 (45 / 0.037 = 1189)
okcoincny undefined 2012.353
okex undefined 515954
```

It's obviously that some exchanges return ticket info although they don't quote in USD at all (like okcoincny).

**Comment by kroitor** [comment] 2017-10-07 15:45
@mkutny for HuobiPRO and Independent Reserve – are you sure that you can always divide like that? Because, traded quoteVolume / baseVolume is not guaranteed to be even close to the actual market price.... It depends on how each particular exchange accounts for traded volume. Some of them can count sells for base Volume, buys for quoteVolume, etc... So these two are not guaranteed to be in direction relation to each other. They are most of the time, but not always, as we can see from these two:
```
huobipro 1254.2214 88.4188633339 (1254 / 88 = 14)
independentreserve 44.90041288 0.03696869 (45 / 0.037 = 1189)
```
What's your opinion on this and what shall we do if that is the case?

**Comment by mkutny** [comment] 2017-10-07 17:21
As for independentreserve - as per their API it looks like they want to return the whole BTC volume across all quoted currencies. Indeed, it's the same for USD, AUD and NZD. We can do nothing about it but this case is an exception.

As for huobipro the story is quite different. I'm sure what gets returned is a ticker for `ETH/BTC` symbol rather than `BTC/USD` (which they don't trade). It's either bug in their API (I hardly read Chinese but it seems they should return `non-existent` in this case) or `ccxt`'s.

The same goes for coinsecure, okcoincny, okex.

Potentially `ccxt` could do a sanity check to ensure requested symbol is at least in the list of exchange's markets although it looks like an enormous amount of work to wrap every API call in it.

**Comment by kroitor** [comment] 2017-10-07 17:27
@mkutny ok, thx a lot for your feedback, we'll try to make it all consistent... will add more tests to it as well, hopefully, soon.
